### PR TITLE
add support for novaseq - not fully tested

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/integrity_checking/13)

### CODE REVIEW

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/integrity_checking/13)* status: 0 of 7 files reviewed, 8 unresolved discussions

___
*[integrity_checking_config.py, line 29 at r1](https://reviewable.io/reviews/moka-guys/integrity_checking/13#-MJkWDbwBEf63HAiAXCW:-MJkWDbwBEf63HAiAXCX:bh5xldu) ([raw file](https://github.com/moka-guys/integrity_checking/blob/c59c79f757ed24828c91814ac4749b26ebf6477f/integrity_checking_config.py#L29)):*
> ```Python
> novaseq = True
> nextseq = False
> if nextseq:
> ```

remove logic step here- change to command line argument for sequencer and set variables in the code
___
*[sequencer_checksum.py, line 47 at r1](https://reviewable.io/reviews/moka-guys/integrity_checking/13#-MJkVyQa1vGj6uwo_REN:-MJkVyQa1vGj6uwo_REO:b-ocidwj) ([raw file](https://github.com/moka-guys/integrity_checking/blob/c59c79f757ed24828c91814ac4749b26ebf6477f/sequencer_checksum.py#L47)):*
> ```Python
> 		# flag to override the minimum wait
> 		self.no_min_wait = False
> ```

add argument for sequencer name here - use this to set self.sequencer_temp_folder and self.mapped_workstation_folder from config file
___
*[sequencer_checksum.py, line 106 at r1](https://reviewable.io/reviews/moka-guys/integrity_checking/13#-MJkVj_u4a1yNYYJQ9dc:-MJkVj_u4a1yNYYJQ9dd:b7wc36i) ([raw file](https://github.com/moka-guys/integrity_checking/blob/c59c79f757ed24828c91814ac4749b26ebf6477f/sequencer_checksum.py#L106)):*
> ```Python
> 					# hide 
> 					root.withdraw()
> 					tkMessageBox.showinfo("Integrity check complete","Integrity check passed")
> ```

add runfolder name here
___
*[sequencer_checksum.py, line 113 at r1](https://reviewable.io/reviews/moka-guys/integrity_checking/13#-MJkVlOE1j5kKNh0b4-u:-MJkVlOE1j5kKNh0b4-v:b7wc36i) ([raw file](https://github.com/moka-guys/integrity_checking/blob/c59c79f757ed24828c91814ac4749b26ebf6477f/sequencer_checksum.py#L113)):*
> ```Python
> 					# hide 
> 					root.withdraw()
> 					tkMessageBox.showerror("Integrity check complete","Integrity check failed - please do not use this sequencer and inform the Bioinformatics team immediately")
> ```

add runfolder name here
___
*[sequencer_checksum.py, line 127 at r1](https://reviewable.io/reviews/moka-guys/integrity_checking/13#-MJkV3hAECDIUlNxLYEk:-MJkV3hAECDIUlNxLYEl:b7qrq3a) ([raw file](https://github.com/moka-guys/integrity_checking/blob/c59c79f757ed24828c91814ac4749b26ebf6477f/sequencer_checksum.py#L127)):*
> ```Python
> 		# message box size
> 		window.minsize(width=666,height=66) 
> 		# message box title
> ```

# add to comments that the novaseq can process 2 runs at a time - add the run id to the message box 
___
*[sequencer_checksum.py, line 197 at r1](https://reviewable.io/reviews/moka-guys/integrity_checking/13#-MJkVIYg56iZZtnZjVFz:-MJkVIYg56iZZtnZjVG-:b-3wdsd7) ([raw file](https://github.com/moka-guys/integrity_checking/blob/c59c79f757ed24828c91814ac4749b26ebf6477f/sequencer_checksum.py#L197)):*
> ```Python
> 		if self.debug:
> 			print "in prepare_checksum_calculations"
> 		print "in prepare_checksum_calculations"
> ```

#remove print statements - or leave them there - won't affect the scheduled tasks but may be useful for when running manually
___
*[sequencer_checksum.py, line 327 at r1](https://reviewable.io/reviews/moka-guys/integrity_checking/13#-MJkVWHQ0M_GtYl84kyh:-MJkVWHQ0M_GtYl84kyi:bjvxoag) ([raw file](https://github.com/moka-guys/integrity_checking/blob/c59c79f757ed24828c91814ac4749b26ebf6477f/sequencer_checksum.py#L327)):*
> ```Python
> 		
> 
> 	def identify_missing_files_nextseq(self):
> ```

add function for novaseq
___
*[sequencer_checksum.py, line 384 at r1](https://reviewable.io/reviews/moka-guys/integrity_checking/13#-MJkVqzyD4GUBGvAO60k:-MJkVqzyD4GUBGvAO60l:b-ug7qgg) ([raw file](https://github.com/moka-guys/integrity_checking/blob/c59c79f757ed24828c91814ac4749b26ebf6477f/sequencer_checksum.py#L384)):*
> ```Python
> 	# add debug argument which is set to true if argument given.
> 	parser.add_argument('--debug', action='store_true', help="Turn debug mode on.")
> 	parser.add_argument('--no_min_wait', action='store_true', help="skips any minimum wait before calculating checksum.")
> ```

add argument for sequencer name

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/integrity_checking/13)* status: 0 of 505 files reviewed, 6 unresolved discussions

___
*[integrity_checking_config.py, line 29 at r1](https://reviewable.io/reviews/moka-guys/integrity_checking/13#-MJkWDbwBEf63HAiAXCW:-MRW3dGJEdd_PkQNR8IM:b-tfydpm) ([raw file](https://github.com/moka-guys/integrity_checking/blob/c59c79f757ed24828c91814ac4749b26ebf6477f/integrity_checking_config.py#L29)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

remove logic step here- change to command line argument for sequencer and set variables in the code
</blockquote></details>

will add as issue for next time
___
*[sequencer_checksum.py, line 47 at r1](https://reviewable.io/reviews/moka-guys/integrity_checking/13#-MJkVyQa1vGj6uwo_REN:-MRW3bwjB7YghpxBQmP9:b-tfydpm) ([raw file](https://github.com/moka-guys/integrity_checking/blob/c59c79f757ed24828c91814ac4749b26ebf6477f/sequencer_checksum.py#L47)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

add argument for sequencer name here - use this to set self.sequencer_temp_folder and self.mapped_workstation_folder from config file
</blockquote></details>

will add as issue for next time
___
*[sequencer_checksum.py, line 106 at r1](https://reviewable.io/reviews/moka-guys/integrity_checking/13#-MJkVj_u4a1yNYYJQ9dc:-MRW3_l10Puem_gQDkg1:b-tfydpm) ([raw file](https://github.com/moka-guys/integrity_checking/blob/c59c79f757ed24828c91814ac4749b26ebf6477f/sequencer_checksum.py#L106)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

add runfolder name here
</blockquote></details>

will add as issue for next time
___
*[sequencer_checksum.py, line 113 at r1](https://reviewable.io/reviews/moka-guys/integrity_checking/13#-MJkVlOE1j5kKNh0b4-u:-MRW3Y7l4ZwCD5gFhD44:bml8zdi) ([raw file](https://github.com/moka-guys/integrity_checking/blob/c59c79f757ed24828c91814ac4749b26ebf6477f/sequencer_checksum.py#L113)):*
> will add as issue for next time
___
*[sequencer_checksum.py, line 127 at r1](https://reviewable.io/reviews/moka-guys/integrity_checking/13#-MJkV3hAECDIUlNxLYEk:-MRW3aujDjPp4gDUpmBN:b-tfydpm) ([raw file](https://github.com/moka-guys/integrity_checking/blob/c59c79f757ed24828c91814ac4749b26ebf6477f/sequencer_checksum.py#L127)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

# add to comments that the novaseq can process 2 runs at a time - add the run id to the message box 
</blockquote></details>

will add as issue for next time
___
*[sequencer_checksum.py, line 197 at r1](https://reviewable.io/reviews/moka-guys/integrity_checking/13#-MJkVIYg56iZZtnZjVFz:-MRW3wKQ9NvfvuabKa-_:bb7f2mf) ([raw file](https://github.com/moka-guys/integrity_checking/blob/c59c79f757ed24828c91814ac4749b26ebf6477f/sequencer_checksum.py#L197)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

#remove print statements - or leave them there - won't affect the scheduled tasks but may be useful for when running manually
</blockquote></details>

done
___
*[sequencer_checksum.py, line 327 at r1](https://reviewable.io/reviews/moka-guys/integrity_checking/13#-MJkVWHQ0M_GtYl84kyh:-MRW3PJoBa4W9vP23Hwl:bb7f2mf) ([raw file](https://github.com/moka-guys/integrity_checking/blob/c59c79f757ed24828c91814ac4749b26ebf6477f/sequencer_checksum.py#L327)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

add function for novaseq
</blockquote></details>

done
___
*[sequencer_checksum.py, line 384 at r1](https://reviewable.io/reviews/moka-guys/integrity_checking/13#-MJkVqzyD4GUBGvAO60k:-MRW3RaP0uYJpGjU2V51:b-tfydpm) ([raw file](https://github.com/moka-guys/integrity_checking/blob/c59c79f757ed24828c91814ac4749b26ebf6477f/sequencer_checksum.py#L384)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

add argument for sequencer name
</blockquote></details>

will add as issue for next time

**Review by aledj2 — COMMENTED** [review]
As Graeme and I have both worked on this I have also reviewed all changes made.

> *[Reviewable](https://reviewable.io/reviews/moka-guys/integrity_checking/13#-:-MRW4bmhBdmKdicqxqV5:b30mkva)* status: 0 of 505 files reviewed, 4 unresolved discussions

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/integrity_checking/13)* status: 0 of 505 files reviewed, all discussions resolved

___
*[sequencer_checksum.py, line 47 at r1](https://reviewable.io/reviews/moka-guys/integrity_checking/13#-MJkVyQa1vGj6uwo_REN:-MRW4tjk9yW0us-sfdQW:bbpd33m) ([raw file](https://github.com/moka-guys/integrity_checking/blob/c59c79f757ed24828c91814ac4749b26ebf6477f/sequencer_checksum.py#L47)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

will add as issue for next time
</blockquote></details>

done #15 
___
*[sequencer_checksum.py, line 106 at r1](https://reviewable.io/reviews/moka-guys/integrity_checking/13#-MJkVj_u4a1yNYYJQ9dc:-MRW51ae-g4s0z1P4vZu:b-fntixf) ([raw file](https://github.com/moka-guys/integrity_checking/blob/c59c79f757ed24828c91814ac4749b26ebf6477f/sequencer_checksum.py#L106)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

will add as issue for next time
</blockquote></details>

done #14
___
*[sequencer_checksum.py, line 113 at r1](https://reviewable.io/reviews/moka-guys/integrity_checking/13#-MJkVlOE1j5kKNh0b4-u:-MRW530SACBCT9Nn7NT9:b-fntixf) ([raw file](https://github.com/moka-guys/integrity_checking/blob/c59c79f757ed24828c91814ac4749b26ebf6477f/sequencer_checksum.py#L113)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> will add as issue for next time
</blockquote></details>

done #14
___
*[sequencer_checksum.py, line 127 at r1](https://reviewable.io/reviews/moka-guys/integrity_checking/13#-MJkV3hAECDIUlNxLYEk:-MRW54tU10vucbhwE8M-:b-fntixf) ([raw file](https://github.com/moka-guys/integrity_checking/blob/c59c79f757ed24828c91814ac4749b26ebf6477f/sequencer_checksum.py#L127)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

will add as issue for next time
</blockquote></details>

done #14

**Comment by Graeme-Smith** [comment]
:lgtm:

**Review by Graeme-Smith — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 500 of 500 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/integrity_checking/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Pull request merged**
